[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
kernel_api = { path = "../kernel_api" }
limine = { version = "0.3.1", features = ["uuid"] }
spin = "0.9.8"
uuid = { version = "1.12.1", default-features = false }
